CREATE TYPE "SaleUnit" AS ENUM ('EACH', 'LB');

ALTER TABLE "Product"
  ADD COLUMN "saleUnit" "SaleUnit" NOT NULL DEFAULT 'EACH',
  ALTER COLUMN "stock" TYPE DOUBLE PRECISION USING "stock"::DOUBLE PRECISION;

ALTER TABLE "OrderItem"
  ADD COLUMN "saleUnit" "SaleUnit" NOT NULL DEFAULT 'EACH',
  ALTER COLUMN "quantity" TYPE DOUBLE PRECISION USING "quantity"::DOUBLE PRECISION;
