ALTER TABLE "Product" ADD COLUMN "taxable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "taxCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "taxable" BOOLEAN NOT NULL DEFAULT false;
